### ISSUE TITLE
score doesn’t reopen with right zoom

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1275] opened 2021-08-06 10:55 UTC
https://user-images.githubusercontent.com/113982/128500015-41d1cc55-57ef-4c02-9a21-4cb93486dbda.mov

it can also be discussed why the default zoom is twice the default duration…

**Comment by jcelerier** [comment] 2021-08-19 16:48
dupe of #584

**Closed as completed** 2021-08-19 20:07 UTC
