### ISSUE TITLE
double clic

### ISSUE THREAD

**Issue by nicolight** [ossia/score#828] opened 2018-09-09 10:44 UTC
Silly question : when I double clic on an event, it opens it.
How do I come back to the global view of the entire timeline?

**Comment by bltzr** [comment] 2018-09-09 11:15
you can either:
- click in the path on the main interval header
- ctrl/cmd + up arrow

**Comment by bltzr** [comment] 2018-09-09 11:17
closing the issue
 also, could you ask those kinf of questions on the [forum](http://forum.ossia.io/c/score) instead ? (so we can leave that as a resource for other users)
issues are generally for tasks (bugs, or feature requests), so they get closed once the problem is fixed, and in this case, the info (which might be useful for others) gets lost

**Closed as completed by bltzr** 2018-09-09 11:17 UTC

**Comment by nicolight** [comment] 2018-09-09 15:14
I use score 1.0.0-b38 on windows.

It doesn’t work with arrows: ctrl+arrow gives the same result that arrow key: it moves the contents.

But I hadn’t realized the names were a clickable path !

thanks
kind regards
Nicolas

 

 

 

 

 

De : Pascal Baltazar [mailto:notifications@github.com] 
Envoyé : dimanche 9 septembre 2018 13:15
À : OSSIA/score
Cc : nicolight; Author
Objet : Re: [OSSIA/score] double clic (#828)

 

you can either:

*	click in the path on the main interval header
*	ctrl/cmd + up arrow

**Comment by jcelerier** [comment] 2018-09-09 15:36
>  It doesn’t work with arrows: ctrl+arrow gives the same result that arrow key: it moves the contents. 

I think that this only implemented in 2.0 and later. Thanks to you for the report :)

**Comment by jcelerier** [comment] 2018-09-09 15:38
@jln- maybe this can be put in the doc (the cmd-arrow stuff) ? https://ossia.github.io/score/in_depth/scenario_process/index.html

**Comment by nicolight** [comment] 2018-09-09 16:59
Sure! but it does not concern scenarios only so it could be better to put it in the first steps…

regards.

Nicolas

 

De : Jean-Michaël Celerier [mailto:notifications@github.com] 
Envoyé : dimanche 9 septembre 2018 17:38
À : OSSIA/score
Cc : nicolight; Author
Objet : Re: [OSSIA/score] double clic (#828)

 

@jln- <https://github.com/jln->  maybe this can be put in the doc (the cmd-arrow stuff) ? https://ossia.github.io/score/in_depth/scenario_process/index.html
