### ISSUE TITLE
Record crash

### ISSUE THREAD

**Issue by avilleret** [ossia/score#184] opened 2016-05-25 08:00 UTC
To reproduce :
- right click on a blank scenario and select Process -> Record [automation from here OR messages]
- press play
- then stop

here is the backtrace : https://gist.github.com/avilleret/736cde5540bec6d3e098597846577487

this is on Mac OS X 10.11.4 with i-score v1.0.0-a68

**Comment by avilleret** [comment] 2016-05-25 08:01
it is also crashing when selecting a device's root node before choosing 'Record'

**Comment by avilleret** [comment] 2016-05-25 08:16
here is a crash log on ubuntu 16.04 with i-score 1.0.0-a68 (I had build error with a68 on Ubuntu 16.04 for now) : https://gist.github.com/avilleret/56467ac47e9cd82959154f3f54a031f7

**Comment by avilleret** [comment] 2016-05-25 08:52
on Ubuntu 16.04, 09c215c still suffer from this

**Comment by bltzr** [comment] 2016-05-31 12:38
What else did you do ?
Here it works with several parameters... (I tried with 32 of them, selected directly - i.e. not from the parent node) 
Though, when selecting the root of a device, recording while moving stuff, and then connecting to the start of the scenario, I get a behavior of the utmost peculiarity:
![mai-31-2016 14-38-51](https://cloud.githubusercontent.com/assets/113982/15674516/6f0a684a-273d-11e6-84e9-7c6e5a4ac747.gif)

**Comment by bltzr** [comment] 2016-05-31 12:58
Though, I also had a crash when selecting a parent node (with about 40 children parameters, with several levels of hierarchy):
https://gist.github.com/bltzr/ce30146e79bd59663066b57df7df5490
Is it similar ? (both seem to be talking about "cohesion", but I don't know what that means...)

**Comment by jcelerier** [comment] 2016-05-31 13:40
@bltzr  could you send me a save file (and tell me what you were recording) so that I can try ? thanks !

**Comment by bltzr** [comment] 2016-05-31 13:44
here you go ! 
I was recording the root node (Nebula)
[testRecAll.scorejson.zip](https://github.com/OSSIA/i-score/files/291219/testRecAll.scorejson.zip)
this is reproducible

**Comment by jcelerier** [comment] 2016-06-01 08:28
I fixed some bugs but I never had a crash while trying to record the whole nebula hierarchy (there are 182 recordable parameters in here)

**Comment by jcelerier** [comment] 2016-06-01 09:13
(also to have better precision when recording I slowed the GUI refresh rate when there are many curves being recorded)

**Comment by bltzr** [comment] 2016-06-10 16:29
@avilleret can you test, I don't think it crashes anymore...

**Comment by jcelerier** [comment] 2016-11-07 17:37
Closing since I refactored / changed this code a lot and the stack trace isn't even meaningful anymore.

**Closed as completed by jcelerier** 2016-11-07 17:37 UTC
Labels: need testing
