### ISSUE TITLE
Left side windows resize dosen't stick

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#934] opened 2019-04-08 10:24 UTC
![vokoscreen-2019-04-08_12-21-39](https://user-images.githubusercontent.com/26526517/55717165-065d0900-59f9-11e9-912b-c037503b6c23.gif)

Strangely, It can be fixed by closing the right side windows.

**Comment by jcelerier** [comment] 2019-04-09 17:58
huh, I tried but I cannot reproduce this one

**Comment by jcelerier** [comment] 2019-05-01 06:56
closing because I think it's fixed, isn't it ?

**Closed as completed by jcelerier** 2019-05-01 06:56 UTC

**Comment by thibaudk** [comment] 2019-05-01 11:52
Yes it is,
Well done !
