### ISSUE TITLE
High Sierra?

### ISSUE THREAD

**Issue by stirringdesert** [ossia/score#1307] opened 2021-09-27 18:07 UTC
Links in the old thread about this are dead. Is there any way I can run Ossia on High Sierra?

**Comment by jcelerier** [comment] 2021-09-29 12:57
hi ! for now we have reverted it to 10.14 minimum as there were some bugs suspected to be caused by the 10.13 minimum version. 

For the final release I'll try to make an additional 10.13 build, but please note that due to Apple explicitely not supporting newer C++ standards in 10.13, this means that some safeties have to be disabled which may cause strange crashes at time..

**Comment by jcelerier** [comment] 2021-09-29 12:59
(see https://stackoverflow.com/a/53868971/1495627 for the headache this causes...)

**Comment by jcelerier** [comment] 2022-02-12 10:59
hello, the latest release should work on High Sierra again, can you test it to confirm ? https://github.com/ossia/score/releases/tag/v3.0.3

**Comment by jcelerier** [comment] 2022-02-14 10:05
closing the issue, please reopen if you notice issues :)

**Closed as completed by jcelerier** 2022-02-14 10:05 UTC
Labels: macOS
