### ISSUE TITLE
Doesn't seem to be a way to snap notes in the midi piano roll to grid?

### ISSUE THREAD

**Issue by featherfurl** [ossia/score#1385] opened 2022-04-16 02:08 UTC
I noticed the beta release notes for v3 suggest the addition of a grid snapping system. If this setting is what became the "magnetism on musical metrics" option it works for the main timeline but not for the midi piano roll.

Bonus thoughts:

An option to be able to grid snap automation curves would be super useful too.

**Comment by jcelerier** [comment] 2022-04-17 09:44
dupe of #1153

**Closed as completed by jcelerier** 2022-04-17 09:44 UTC
