### ISSUE TITLE
recording automation seems to fail

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#474] opened 2017-05-31 15:18 UTC
Wether it is for one parameter or 66 (as in the joined score when recording de Reaper device), 
i-score starts lagging after a few seconds before eventually freezing. 
Is it a bug or is there more to it than simply selecting what to record and choosing "record automation from here" in the score?

Also the recording dose not start when controlling a parameter through a mapping process.
Will try it with a Javascript process now.   

[ambicontrol.scorejson.zip](https://github.com/OSSIA/i-score/files/1041897/ambicontrol.scorejson.zip)

**Comment by jcelerier** [comment] 2017-05-31 15:42
hmm that's weird, I tried recording the whole Reaper device (for roughly 30 seconds) and I don't see any kind of freeze or even slowness.
Is reaper sending changes all the time, or only when a parameter actually changes ?

**Comment by pchdev** [comment] 2017-06-01 11:47
when a parameter changes if I remember correctly

**Comment by bltzr** [comment] 2017-10-10 17:07
is that still the case ?

**Comment by jcelerier** [comment] 2019-03-25 18:40
closing because I can't reproduce - reopen if it's still an issue

**Closed as completed by jcelerier** 2019-03-25 18:40 UTC
