### ISSUE TITLE
2D and possibly 3D spline editor

### ISSUE THREAD

**Issue by lossius** [ossia/score#36] opened 2015-09-11 17:32 UTC
_This is a feature request._

I'm able to create automations of Jamoma parametes of type decimal. I have attempted to create automations of source positions. These are of type array and contains three decimals (x, y and z). They are set up using the position dataspace, so that they in Max can be addressed using Cartesian and Spherical coordinates interchangeably.

One of the benefits of this in Max is that if you ramp to new values using xyz, the position moves along a straight line, while if you ramp using aed coordinates, it will move along spiraling trajectories.

I'm sure that there are some design issues to be considered here, but it would be nice to be able to control positions in i-score.

**Comment by jcelerier** [comment] 2016-10-26 09:59
almost there :)

**Comment by jcelerier** [comment] 2016-10-26 10:16
Here's how it behaves, for colors for instance.
![color](https://cloud.githubusercontent.com/assets/2772730/19722225/0979edcc-9b76-11e6-933c-d16abbaabd6b.gif)
The first comment is wrong, it's R=0 G=1 B=0

**Comment by bltzr** [comment] 2017-05-18 06:02
AFAIK this is implemented and working now, so I'm closing the issue
no doubt we'll look into it in Bergen

**Comment by jcelerier** [comment] 2017-05-18 07:28
hmmm for me it's not quite finished. I'd like to have a "2D spline" process to make paths properly.

**Comment by jcelerier** [comment] 2017-05-24 09:58
actually this makes it a duplicate of #459 so closing this one

**Closed as completed by jcelerier** 2017-05-24 09:58 UTC
