### ISSUE TITLE
crash when right-clicking in the device explorer

### ISSUE THREAD

**Issue by jln-** [ossia/score#1087] opened 2020-10-12 23:16 UTC
I am afraid I cannot bring more info. As far as I remember:

On a freshly created score.

Right click to add OSC device (no other device opened)

Right click again on the device explorer and kaboom.

scenario was empty and not running. Only had Max opened in the background with Ossia Overview patcher if that matters.

https://gist.github.com/jln-/5144b5447678ac3ac1fcadcee7c02496

**Comment by jcelerier** [comment] 2020-10-14 09:32
can't seem to be able to reproduce that one on linux, will have to try on mac -_-

**Comment by jln-** [comment] 2020-10-14 12:20
I cant either. So far it only did happened once.

**Comment by jcelerier** [comment] 2020-10-22 23:23
closing, tried again but definitely can't reproduce even on mac

**Closed as completed by jcelerier** 2020-10-22 23:23 UTC
