### ISSUE TITLE
zoom level not correctly recalled when loading score

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1261] opened 2021-07-24 14:54 UTC
scenarios open at full out zoom when reopened

**Comment by bltzr** [comment] 2021-07-24 14:55
[testPd.score.zip](https://github.com/ossia/score/files/6872621/testPd.score.zip)
at least this one

**Comment by jcelerier** [comment] 2021-07-24 18:08
duplicate of #584

**Closed as completed by jcelerier** 2021-07-24 18:08 UTC
