### ISSUE TITLE
Crash when evaluating a trigger

### ISSUE THREAD

**Issue by reno-** [ossia/score#48] opened 2015-10-23 14:39 UTC
Play a scenario with a trigger… crash when evaluating the trigger
https://gist.github.com/reno-/26e5c80c0eb15f94b6ac

**Comment by theod** [comment] 2015-11-05 15:30
I tried to reproduce the bug with this scenario without success (you have to remove the .txt extension before !). this is working with j.minuit_Device.maxhelp exemple, you have to turn the /myinput/file/play parameter to on to trig the next.

[test - trigger.scorejson.txt](https://github.com/OSSIA/i-score/files/28113/test.-.trigger.scorejson.txt)

is it working ?
if yes would you provide me a project where it is failing ?

**Comment by theod** [comment] 2015-12-08 16:56
I close it as it seems we are not able to reproduce it and as many changes occurred into the execution mechanism since this issue have been opened.

**Closed as completed by theod** 2015-12-08 16:56 UTC
Labels: need testing
