### ISSUE TITLE
[gfx] Memory leak with Qt5 builds when displaying shaders

### ISSUE THREAD

**Issue by yiids** [ossia/score#1437] opened 2022-11-14 22:04 UTC
There seems to be a memory leak, perhaps in the shader device. A simple score with one shader device that loops continuously keeps eating memory. Attached score as an example:
[memleak.zip](https://github.com/ossia/score/files/10007436/memleak.zip)

When looping a video file for example, the memory usage stays the same,

OS: Debian 11 (Bullseye)
Score version: 3.1.4 Appimage

**Comment by jcelerier** [comment] 2022-11-15 19:20
hmm this is weird, I tried on my machine letting it run for five minutes and memory usage did not increase by one megabyte. I'll try on your OS.

**Comment by jcelerier** [comment] 2022-11-15 21:55
okay, I can reproduce on the Qt 5 version, but it seems fixed on Qt 6 ; it looks like a bug within Qt. I'll update the Qt version for the next release

**Comment by jcelerier** [comment] 2024-02-07 03:13
Qt 6 has been used for a year now :)

**Closed as completed by jcelerier** 2024-02-07 03:13 UTC
