### ISSUE TITLE
Udefined behaviour in interpolation process

### ISSUE THREAD

**Issue by eirikblekesaune** [ossia/score#530] opened 2017-06-21 14:17 UTC
Using this composition I am doing the following in the end of the score:
1. I am defining a int value with the path '/bing'
2. Two states with values 200 and 100 respectively.
3. Added a interpolation process between these states where the break point function goes from 0.0 to 1.0 and back to 0.0.
4. This works fine.
5. The second interpolation offsets the start and the end break points, so that there are no break points at the beginning and the end.
6. The start and end states are equal to the previous process.

What happens in the process:
It starts going upwards from 0. When it reaches the last break point (having no break points after it) the value stops at 169, but keeps sending the repeated value until the end of the process. When the the progress reaches the end state it sends the last value of 100.

I would expect that no break point would mean "send no value".

Possible simple fix: If the functionality of the interpolation process is dependant on having break point being declared at the end and the beginning, moving them in the GUI could be prevented?

[Interpolation.scorejson.zip](https://github.com/OSSIA/i-score/files/1091724/Interpolation.scorejson.zip)

**Comment by bltzr** [comment] 2017-06-21 15:38
> Possible simple fix: If the functionality of the interpolation process is dependant on having break point being declared at the end and the beginning, moving them in the GUI could be prevented?

since the start value is sent at start time, and the end value at end time, I'd be for preventing to move the first and last points resp. from the bottomleft and topright corner....
but maybe that's too drastic ?
(and @lossius was critical of the process itself)

also, we noticed with @blacksound that (with a simple, straight line) the start state was not sent, just the value after

**Comment by jcelerier** [comment] 2017-06-23 17:56
> since the start value is sent at start time, and the end value at end time, I'd be for preventing to move the first and last points resp. from the bottomleft and topright corner....
but maybe that's too drastic ?

The problem is that then you can't do this : 
<img width="1031" alt="inside" src="https://user-images.githubusercontent.com/2772730/27494404-0698d72c-584e-11e7-9c25-21fd958ac5b2.png">
<img width="1030" alt="outside" src="https://user-images.githubusercontent.com/2772730/27494434-1f2f4a96-584e-11e7-8a56-0dbb35d2e0a6.png">

**Comment by bltzr** [comment] 2017-06-25 12:44
sure, and there's also a bunch of other things that we cannot do, but I think, with @blacksound that this (and maybe changing slightly the graphic design, such as proposed in #580) would probably help making the purpose of this process more clear.

**Comment by bltzr** [comment] 2017-06-25 12:46
the problem with doing what you're showing above (and generally when combining interpolation and triggers), is that there will be a leap at the en of the process if it's triggered before the "default" duration
I guess that's what it is...

**Comment by bltzr** [comment] 2017-07-14 09:38
the other - opposed - solution would be to decorrelate the interpolation process from the states, as @lossius proposed - which would make everything clearer
then, we could have one state (i.e. collection of address/value pairs) assigned to the "bottom" of the slot, and another one (with the same addresses, but other sets of values) to the "top" (with some design such as (but graphically better than) https://github.com/OSSIA/i-score/issues/580 - and then y=0 would mean sending the "bottom" "state", and y=1 sending the top "state", and interpolating in between
another difference would be that this updated process would not only work with tuple parameters, but with any kind of parameters (a collection of them)
also, @lossius proposed that it would be possible to "break down" this interpolation into as many equivalent automation processes (but I guess that's for even later...)

**Comment by jcelerier** [comment] 2021-04-29 15:30
disabling the interpolation process, it will have to be remade at some point but as such it's very broken

**Closed as completed by jcelerier** 2021-04-29 15:30 UTC
