### ISSUE TITLE
Score send the wrong type of the value of an Int slider

### ISSUE THREAD

**Issue by Toine-ddt** [ossia/score#1236] opened 2021-06-15 13:23 UTC
![intSlider](https://user-images.githubusercontent.com/65868237/122060047-83f8dc80-cded-11eb-85cb-30743e6ab2e8.JPG)

Message sent by score :
`{"uuid":"348b80a4-45dc-4f70-8f5f-6546c85089a2","ObjectName":"Inlet","id":2,"Hidden":true,"Custom":"Octave","Exposed":"octave","Value":{"Float":6},"Domain":{"Int":{"Min":1,"Max":7}}}`

Type Value : Float -> Int

**Comment by jcelerier** [comment] 2021-07-24 09:40
hum weird,here I get that: 

```

        {
            "uuid": "348b80a4-45dc-4f70-8f5f-6546c85089a2",
            "ObjectName": "Inlet",
            "id": 2,
            "Hidden": true,
            "Custom": "Octave",
            "Exposed": "octave",
            "Value": {
                "Int": 6
            },
            "Domain": {
                "Int": {
                    "Min": 1,
                    "Max": 7
                }
            }
        },
```

can you send me your score ?

**Comment by Toine-ddt** [comment] 2021-07-26 07:26
[comobox.zip](https://github.com/ossia/score/files/6876325/comobox.zip)
but I made a new scenario with an arpegiator and I can't reproduce the bug

**Comment by jcelerier** [comment] 2021-07-26 19:56
okay, can't reproduce either, let's close the issue and reopen it if it reappears

**Closed as completed by jcelerier** 2021-07-26 19:56 UTC
Labels: need repro
