### ISSUE TITLE
min and max params for automation XY

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#825] opened 2018-08-24 18:53 UTC
At the moment, X and Y can only range fro 0 to 1.

This is probably a duplicate but i couldn't find where.

**Comment by jcelerier** [comment] 2018-08-25 07:06
> This is probably a duplicate but i couldn't find where.

no I don't think it's a duplicate, but maybe we should make a single issue for features of this process ? (I made it very quickly as a test so it's fairly lacking)

**Comment by jcelerier** [comment] 2018-09-10 12:01
actually yes, it was a duplicate of https://github.com/OSSIA/score/issues/459

**Closed as completed by jcelerier** 2018-09-10 12:01 UTC
