### ISSUE TITLE
setting OSC rate disables both sending and receiving

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1156] opened 2021-02-12 23:04 UTC
this is using the rate widget in the edition window of the device.

**Comment by jcelerier** [comment] 2021-02-13 09:57
for all protocols ?

**Comment by thibaudk** [comment] 2021-02-13 11:13
It is only available for osc and oscquerry.
for oscquerry, it works if the rate is set on initialization. If it is later edited, I have some weird behavior but that may be on my side

**Comment by jcelerier** [comment] 2021-04-29 15:50
duplicate of #987

**Closed as completed by jcelerier** 2021-04-29 15:50 UTC
