### ISSUE TITLE
Refreshing namespace after having dynamically changed what parameters exists leads to error

### ISSUE THREAD

**Issue by lossius** [ossia/score#35] opened 2015-09-11 17:15 UTC
_It might be that this is a bug with j.modular in Max/Jamoma rather than with i-score._

Steps to reproduce:
1. Start Max
2. Open j.minuit_device.maxhelp
3. Also open j.dbap=.model.maxhelp, and give it the time needed to instantiate itself.
4. Start i-score, and make a new Minuit device with thefault settings. So far - so good.
5. Back in Max, in j.dbap=.model.maxhelp increase the number of sources to 2 in the smallest of the three views that the patch contains. (After having typed "2" into the number box, make sure to hit enter so that the live.number object actually outputs the number.) - If everything is done correctly, you should see two channels in the lower left view, and two yellow dots in the ambimonitor view.
6. Back in -score, refresh the device namespace.

Result: This produce a dialog box with the following error message:

```
Unable to refresh the device: newDevice.
Cause: namespace empty after the update
```
1. Hit the OK button.

Result: /mydbap/sources/number_of_sources has been increased to 2, but /mydbap/sources/source.2 is not being displayed.
1. Quit -score, restart, and make a new Minuit device with default settings.

Result: Now both sources shows up.

So, somehow, either in i-score or in Max/Jamoma/Minuit there is currently an inability to deal with namespaces where it change over time what parameters exist or not.

**Comment by jcelerier** [comment] 2015-09-12 09:47
This looks like a regression,  this used to work a few weeks ago.

**Comment by jcelerier** [comment] 2015-09-12 09:55
@theod it doesn't work (throws an exception) in the Minuit_exploration API example if I replace 

```
minuitDevice->updateNamespace();
```

by 

```
minuitDevice->updateNamespace();
minuitDevice->updateNamespace();
```

**Comment by theod** [comment] 2015-11-05 17:36
fixed ! but it need testing
I assign to you @jcelerier

**Comment by theod** [comment] 2015-12-08 16:20
fixed !

**Closed as completed by theod** 2015-12-08 16:20 UTC
Labels: need testing
