### ISSUE TITLE
[feature request] : add lock mode to state to avoid changing their time position

### ISSUE THREAD

**Issue by avilleret** [ossia/score#491] opened 2017-06-19 18:19 UTC
for example, if I need a 2 seconds constrain I can enter the time precisely in the inspector, but if I clic on the end node, then it might move a little bit and the constrain is no more strictly 2 seconds
so a lock mode to avoid node to move left and right might help me with my fat fingers

**Comment by bltzr** [comment] 2017-06-19 20:58
or maybe it should wait a little (like 200ms) before allowing the drag to move ?

**Comment by pach** [comment] 2017-06-19 22:09
I think the "lock time" option is a really good idea. There is some time when you are completely sure about your scenario time and want to avoid to accidentally change it (which can occur quite fast when you are not completely focused).
I'd use it. :)

Thomas Pachoud 
www.creapach.fr

**Comment by jcelerier** [comment] 2017-06-19 22:15
> I think the "lock time" option is a really good idea. 

okay, I think that someone should devise a strong visual cue in the scenario that show that a particular constraint is locked (so that it's quickly visible in the main score).

**Comment by bltzr** [comment] 2017-06-21 14:01
also, how would we lock a state/duration ?
on the state ?
on the constraint ?

with a shortcut ?
from the inspector ?

I’d say: on the constraint, with both a checkbox (lock, on the right of the « default duration ») and a shortcut (cmd-L ?) when selecting the constraint (and possibly the end state)

opinions ?

**Comment by bltzr** [comment] 2017-06-21 14:05
this said, maybe there’s a bug connected to this because, some times (but I can’t currently reproduce), states were moving when selecting them - independently of finger’s thickness...

**Comment by jln-** [comment] 2017-06-21 14:25
Not sure I correctly get. There are two different things here, isn't it ?

One is than mouse handling should prevent accidental movement so we dont move states (in that regard, Pascal proposition sounds fine).

And another allowing user to explicitly lock something. But that's another problem, isn't it ?

**Comment by pchdev** [comment] 2017-06-21 14:48
> this said, maybe there’s a bug connected to this because, some times (but I can’t currently reproduce), states were moving when selecting them - independently of finger’s thickness...

yeah I have these sometimes too, dunno if it is related to zoom or just mouse super-sensitivity, or qt widget context selection, or something else..

**Comment by jln-** [comment] 2017-06-21 15:03
Do you guys use Apple Magic Mouse ? These kind of accidental mouvement happens really easily when while clicking something your finder also slightly move on the tactile top of the mouse. (I also have the same problem with Affinity Designer which drives me crazy/crazier)

**Comment by pchdev** [comment] 2017-06-21 15:09
I'm testing with a windows-like mouse, and I think it happens when I click slightly out of the state, in forward direction (top-right or bottom-right), is it the same for you guys ?

**Comment by bltzr** [comment] 2017-06-22 08:32
yes, that's it: I had this when clicking a little on the left of the state - IMO this shouldn't happen at all

![juin-22-2017 10-31-43](https://user-images.githubusercontent.com/113982/27424670-1f45b772-5736-11e7-827e-7981681b7a04.gif)

**Comment by bltzr** [comment] 2017-06-27 18:58
maybe the behavior I reported in my last comment should be listed (separately) as a bug, as it is quite embarrassing ?
Is this a hard one, @jcelerier ?

**Comment by jcelerier** [comment] 2017-06-27 19:14
> maybe the behavior I reported in my last comment should be listed (separately) as a bug, as it is quite embarrassing ?

i tried on multiple computers and cannot reproduce it at all :(

**Comment by bltzr** [comment] 2017-10-12 15:40
I found this coment from #585 that might be reviewed, so I'll create a new specific issue for that and close this one here

**Comment by bltzr** [comment] 2017-10-12 15:40
the comment:
> @blueyeti said when we met last week that, in his opinion, the problem came from a bad interaction design, and that there should be a kind of motion threshold in order to avoid moving things by mistake when grabbing them
he said he would also review other softwares in order to see what's the best way to do all of this
so I'm assigning to him

**Closed as completed by bltzr** 2017-10-12 15:40 UTC
