### ISSUE TITLE
[ui] interval min/max duration widget is not resized correctly when enabling bound

### ISSUE THREAD

**Issue by avilleret** [ossia/score#944] opened 2019-05-09 09:52 UTC
![score-interval-duration-widget-issue-2019-05-09_11 48 14](https://user-images.githubusercontent.com/504914/57444646-e5364500-7250-11e9-8800-751139b3565a.gif)

**Comment by jcelerier** [comment] 2019-05-18 10:07
duplicate of #932

**Closed as completed by jcelerier** 2019-05-18 10:07 UTC
