### ISSUE TITLE
Don't allow zooming in when granularity level is reached 

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#53] opened 2015-10-27 10:08 UTC

**Comment by theod** [comment] 2015-12-08 17:03
@jcelerier : what is the trouble exactly in order I test it ? (I can't see any obvious trouble)

**Comment by nvuaille** [comment] 2016-02-19 16:25
The problem is that max zoom is relative to constraint duration. 
So it appears only if you are zooming in a little constraint (few seconds long).
I guess we have to prevent so much zoom (makes no sens to have a microsecond view when a tick is about some millisecond).

**Comment by bltzr** [comment] 2017-05-18 06:03
what about this ?

**Comment by jcelerier** [comment] 2017-05-18 07:30
?

**Comment by bltzr** [comment] 2017-05-18 10:49
If nobody knows what this is about we should maybe close the issue?

**Comment by nvuaille** [comment] 2017-05-18 11:08
I'm not sure of what it means but came it from some questions about the timebar and the zoom:
 - timebar marks disapear when zooming
![first](https://cloud.githubusercontent.com/assets/5503180/26199440/4979f422-3bca-11e7-8e5c-12353c0a5697.PNG)
![second](https://cloud.githubusercontent.com/assets/5503180/26199438/49759c1a-3bca-11e7-94bb-1e84c7d3e312.PNG)

 - zoom max depends on fullview constrains duration: is it a good thing ?

**Comment by jcelerier** [comment] 2017-05-18 12:22
> zoom max depends on fullview constrains duration: is it a good thing ?

I'm now pretty much convinced that it is not :p 

Could we agree on a "maximum" zoom level ? how big should be one millisecond at most ? this would simplify sooooooooo many things

**Comment by bltzr** [comment] 2017-05-19 14:10
I’d say a few pixels (maybe like 5 or 10 ?) per ms at max zoom ?

does that sound like a good figure ?

**Comment by jcelerier** [comment] 2017-05-24 09:58
okay, trying this

**Comment by bltzr** [comment] 2017-05-26 08:24
did this make it into the minimap version ? 

because here's my maximum zoom level for a 10 minutes scenario:

<img width="718" alt="zoom" src="https://cloud.githubusercontent.com/assets/113982/26486944/86dbcf6e-41fd-11e7-9e12-8056440e02a1.png">

**Comment by jcelerier** [comment] 2017-05-26 08:39
> did this make it into the minimap version ?

not yet

**Closed as completed** 2017-05-26 10:09 UTC
