### ISSUE TITLE
Snapping states together

### ISSUE THREAD

**Issue by evanmtp** [ossia/score#759] opened 2018-05-26 16:52 UTC
When you create a new state and drag it over an existing state, the states will snap together, creating a linked line of time intervals.

![snapping1](https://user-images.githubusercontent.com/5342408/40578510-5a3c3e16-60e3-11e8-9dd1-f59e740865ca.gif)

If you try to drag an existing state onto another existing state, however, they won’t snap together and link.

![snapping2](https://user-images.githubusercontent.com/5342408/40578551-bc5b3a16-60e3-11e8-8366-d4d28b1e82d0.gif)

It would seem more consistent to me if the snapping/linking behaviour was the same for both new and already-existing states.

**Comment by jcelerier** [comment] 2018-07-27 08:07
that's mostly a duplicate of #337

**Closed as completed by jcelerier** 2018-07-27 08:07 UTC
