### ISSUE TITLE
Drag multiple objects when they're group selected

### ISSUE THREAD

**Issue by evanmtp** [ossia/score#796] opened 2018-06-30 20:05 UTC
Intuitively I would expect that when you select a bunch of objects and then click + drag on one of them, all of the objects would move as a group. Currently, only the object that you actually click on moves. This can make rearranging complex scenarios laborious.

**Comment by jcelerier** [comment] 2021-04-28 21:06
duplicate of #488

**Closed as completed by jcelerier** 2021-04-28 21:06 UTC
